### ISSUE TITLE
Error: Use of const in strict mode

### ISSUE THREAD

**Issue by iamnewton** [tiniest/headr#1]
```
#1495: $ ./node_modules/.bin/headr dist/styles/legion-grid.flexbox.css --version --homepage > dist/styles/legion-grid.flexbox.css
/Users/chrisopedia/Code/rubicon/legion-grid/node_modules/headr/index.js:3
const FS = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/chrisopedia/Code/rubicon/legion-grid/node_modules/headr/bin/headr:2:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by iamnewton** [comment]
Appears to be the use of ES6, so I transpiled it and replaced with and it works now.

``` javascript
'use strict';

var FS = require('fs');
var PATH = require('path');
var ARGS = require('minimist')(process.argv.slice(2));
var PKG = require(PATH.join(process.cwd(), 'package.json'));
var SPACES = function SPACES(amount) {
  return new Array(amount + 1).join(' ');
};
var TAB = SPACES(ARGS['h-tab-spaces'] + 2 || 2);
var PREFIX = TAB + "*";
var MAIN_PREFIX = SPACES(ARGS['h-tab-spaces'] || 0) + '/**';
var BASE = function BASE() {
  return [MAIN_PREFIX, PREFIX + ' ' + PKG.name + ' - ' + PKG.description, PREFIX];
};
var CHECK_VERSION = function CHECK_VERSION(key) {
  return key === 'version' ? 'v' : '';
};
var CHECK_LABEL = function CHECK_LABEL(key) {
  return ARGS[key].trim ? ARGS[key] : key;
};
var KEYS = function KEYS(key) {
  return PREFIX + ' @' + CHECK_LABEL(key) + ' ' + CHECK_VERSION(key) + PKG[key];
};
var MATCH = function MATCH(key) {
  return PKG[key];
};
var EXTRA = function EXTRA() {
  return Object.keys(ARGS).slice(1).filter(MATCH).map(KEYS);
};
var EOL = [TAB + '*/', ''];

if (ARGS._.length) {
  FS.readFile(ARGS._[0], 'utf8', function (err, stdout) {
    if (err) {
      throw new err();
    }

    console.log(BASE().concat(EXTRA(), EOL, [stdout]).join('\n'));
  });
} else {
  console.log(BASE().concat(EXTRA(), EOL).join('\n'));
}
```

**Comment by heldr** [comment]
@chrisopedia Hi!

This library only works in Node.js 4+ ...but I'm considering to transpile it using babel 6 presets.

Cheers! :tea:

**Comment by iamnewton** [comment]
@heldr k.  You might want to note that in the README so someone else doesn't run into this issue.

**Comment by heldr** [comment]
Makes sense.

BTW NPM already warns once you install it in older versions.
See: https://github.com/tiniest/headr/blob/master/package.json#L9

I'm very busy right now. The doc will be updated ASAP or PR me please!
